import { useState, useCallback } from 'react';
import type { InventoryLot, Mine, Dispatch, AppSettings } from '../types';
import { getCurrencySymbol, formatAmountNumber } from '../utils/currency';
import { formatDisplayDate } from '../utils/dateUtils';
import { playPopSound, playSuccessSound } from '../utils/delight';
import { Capacitor } from '@capacitor/core';
import { Share } from '@capacitor/share';
import IOSConfirmModal from './IOSConfirmModal';
import {
  X,
  Share2,
  Edit2,
  Trash2,
  Package,
  Truck,
  CheckCircle2,
  ExternalLink,
  MapPin,
  Calendar,
  Check,
} from 'lucide-react';

interface StockPreviewModalProps {
  lot: InventoryLot | null;
  mine: Mine | null;
  linkedDispatch?: Dispatch | null;
  settings?: AppSettings;
  onClose: () => void;
  onEdit: (lot: InventoryLot) => void;
  onDelete: (lot: InventoryLot) => void;
  onViewDispatch?: (dispatch: Dispatch) => void;
}

export default function StockPreviewModal({
  lot,
  mine,
  linkedDispatch,
  settings,
  onClose,
  onEdit,
  onDelete,
  onViewDispatch,
}: StockPreviewModalProps) {
  const [toastMsg, setToastMsg] = useState<string | null>(null);
  const [showUsedAlert, setShowUsedAlert] = useState(false);

  const showToast = (msg: string) => {
    setToastMsg(msg);
    setTimeout(() => setToastMsg(null), 2500);
  };

  const curSym = getCurrencySymbol(settings?.currency);

  const handleShare = useCallback(async () => {
    if (!lot) return;

    const billed = lot.billedWeight || lot.tonnage || 0;
    const received = lot.receivedWeight || billed;
    const baseRate = lot.purchaseRate || lot.ratePerTon || mine?.ratePerTon || 0;
    const baseCost = billed * baseRate;
    const loading = lot.loadingCost || 0;
    const fare = lot.freightCost || 0;
    const totalCost = lot.totalValue || (baseCost + loading + fare);
    const landed = lot.landedRate || (received > 0 ? totalCost / received : baseRate);

    const shareText = `*COAL STOCK INFLOW VOUCHER*
*Mine:* ${mine?.name || lot.mineName || 'Mine Stock'}
*Bought From:* ${lot.boughtFrom || lot.supplier || 'N/A'}
*Stored At:* ${lot.storedAt || mine?.location || 'Mine Yard'}
*Date:* ${formatDisplayDate(lot.date)}
----------------------------------------
*WEIGHT BREAKDOWN:*
• Loaded/Billed Weight: ${billed.toFixed(2)} tons
• Received Weight: ${received.toFixed(2)} tons
----------------------------------------
*COST BREAKDOWN:*
• Base Mine Rate: ${curSym} ${formatAmountNumber(baseRate, settings)}/ton
• Coal Cost: ${curSym} ${formatAmountNumber(baseCost, settings)}
${loading > 0 ? `• Loading Charges: ${curSym} ${formatAmountNumber(loading, settings)}\n` : ''}${fare > 0 ? `• Freight / Fare: ${curSym} ${formatAmountNumber(fare, settings)}\n` : ''}----------------------------------------
*TOTAL COST:* ${curSym} ${formatAmountNumber(totalCost, settings)}
*EFFECTIVE RATE:* ${curSym} ${formatAmountNumber(landed, settings)}/ton
----------------------------------------
*Status:* ${linkedDispatch || lot.usedInDispatchId ? `USED IN DISPATCH (${lot.usedInDispatchTruck || linkedDispatch?.truckNumber || 'Dispatched'})` : 'IN YARD STOCK'}

*Generated by ${settings?.businessName || 'Awan Coal Logistics'}*`;

    try {
      if (Capacitor.isNativePlatform()) {
        await Share.share({
          title: `Stock Receipt - ${mine?.name || 'Mine'}`,
          text: shareText,
          dialogTitle: 'Share Stock Inflow Receipt',
        });
        playSuccessSound();
        showToast('Receipt shared!');
        return;
      } else if (navigator.share) {
        await navigator.share({
          title: `Stock Receipt - ${mine?.name || 'Mine'}`,
          text: shareText,
        });
        playSuccessSound();
        showToast('Receipt shared!');
        return;
      }
    } catch {
      // Fallback to clipboard
    }

    if (navigator.clipboard) {
      navigator.clipboard.writeText(shareText);
      playPopSound();
      showToast('Receipt copied to clipboard!');
    }
  }, [lot, mine, linkedDispatch, settings, curSym]);

  if (!lot) return null;

  const billedWeight = lot.billedWeight || lot.tonnage || 0;
  const receivedWeight = lot.receivedWeight || billedWeight;
  const weightDiff = receivedWeight - billedWeight;
  const baseRate = lot.purchaseRate || lot.ratePerTon || mine?.ratePerTon || 0;
  const baseCoalCost = billedWeight * baseRate;
  const loading = lot.loadingCost || 0;
  const fare = lot.freightCost || 0;
  const totalCost = lot.totalValue || (baseCoalCost + loading + fare);
  const landedRate = lot.landedRate || (receivedWeight > 0 ? totalCost / receivedWeight : baseRate);

  const isUsed = Boolean(linkedDispatch || lot.usedInDispatchId);
  const usedTruck = lot.usedInDispatchTruck || linkedDispatch?.truckNumber;
  const usedParty = lot.usedInPartyName || linkedDispatch?.factoryName;

  return (
    <div
      className="ios-modal-overlay"
      style={{
        position: 'fixed',
        inset: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.65)',
        backdropFilter: 'blur(8px)',
        WebkitBackdropFilter: 'blur(8px)',
        zIndex: 9999,
        display: 'flex',
        alignItems: 'flex-end',
        justifyContent: 'center',
        padding: 0,
      }}
      onClick={onClose}
    >
      <div
        className="ios-action-sheet"
        style={{
          width: '100%',
          maxWidth: 560,
          background: 'var(--bg-card)',
          borderTopLeftRadius: 24,
          borderTopRightRadius: 24,
          maxHeight: '90vh',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: '0 -10px 40px rgba(0,0,0,0.3)',
          overflow: 'hidden',
          animation: 'slideUpSheet 0.25s cubic-bezier(0.1, 0.9, 0.2, 1)',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Grabber Handle */}
        <div style={{ display: 'flex', justifyContent: 'center', paddingTop: 10, paddingBottom: 6 }}>
          <div style={{ width: 36, height: 5, borderRadius: 3, background: 'var(--label-tertiary)', opacity: 0.4 }} />
        </div>

        {/* Modal Header */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '8px 16px 12px',
            borderBottom: '0.5px solid var(--separator)',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div
              style={{
                width: 36,
                height: 36,
                borderRadius: 10,
                background: isUsed ? 'rgba(175, 82, 222, 0.14)' : 'rgba(52, 199, 89, 0.14)',
                color: isUsed ? 'var(--ios-purple, #af52de)' : 'var(--ios-green)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <Package size={20} />
            </div>
            <div>
              <h2 style={{ fontSize: 17, fontWeight: 700, margin: 0, color: 'var(--label-primary)' }}>
                Stock Inflow Entry
              </h2>
              <div style={{ fontSize: 12, color: 'var(--label-secondary)' }}>
                {mine?.name || lot.mineName || 'Coal Mine'}
              </div>
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <button
              type="button"
              onClick={handleShare}
              style={{
                width: 36,
                height: 36,
                borderRadius: 18,
                background: 'var(--fill-secondary)',
                border: 'none',
                color: 'var(--label-primary)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                cursor: 'pointer',
              }}
              title="Share Voucher"
            >
              <Share2 size={17} />
            </button>

            <button
              type="button"
              onClick={() => {
                onClose();
                onEdit(lot);
              }}
              style={{
                width: 36,
                height: 36,
                borderRadius: 18,
                background: 'var(--fill-secondary)',
                border: 'none',
                color: 'var(--ios-blue)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                cursor: 'pointer',
              }}
              title="Edit Stock"
            >
              <Edit2 size={17} />
            </button>

            <button
              type="button"
              onClick={() => {
                if (isUsed) {
                  playPopSound();
                  setShowUsedAlert(true);
                  return;
                }
                onClose();
                onDelete(lot);
              }}
              style={{
                width: 36,
                height: 36,
                borderRadius: 18,
                background: 'var(--fill-secondary)',
                border: 'none',
                color: isUsed ? 'var(--label-tertiary)' : 'var(--ios-red)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                cursor: isUsed ? 'not-allowed' : 'pointer',
                opacity: isUsed ? 0.45 : 1,
              }}
              title={isUsed ? 'Cannot delete: used in dispatch' : 'Delete Stock'}
            >
              <Trash2 size={17} />
            </button>

            <button
              type="button"
              onClick={onClose}
              style={{
                width: 36,
                height: 36,
                borderRadius: 18,
                background: 'var(--fill-secondary)',
                border: 'none',
                color: 'var(--label-secondary)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                cursor: 'pointer',
              }}
              title="Close"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Toast */}
        {toastMsg && (
          <div
            style={{
              margin: '8px 16px 0',
              padding: '8px 12px',
              borderRadius: 10,
              background: 'var(--fill-secondary)',
              border: '0.5px solid var(--separator)',
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              fontSize: 13,
              color: 'var(--ios-green)',
              fontWeight: 600,
            }}
          >
            <Check size={16} />
            <span>{toastMsg}</span>
          </div>
        )}

        {/* Modal Scrollable Body */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '16px 16px 32px' }}>
          {/* Status Banner */}
          {isUsed ? (
            <div
              style={{
                marginBottom: 16,
                padding: '12px 14px',
                borderRadius: 14,
                background: 'rgba(175, 82, 222, 0.12)',
                border: '0.5px solid rgba(175, 82, 222, 0.3)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                gap: 12,
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <CheckCircle2 size={20} style={{ color: 'var(--ios-purple, #af52de)', flexShrink: 0 }} />
                <div>
                  <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--ios-purple, #af52de)' }}>
                    Coal Used in Dispatch
                  </div>
                  <div style={{ fontSize: 12, color: 'var(--label-secondary)', marginTop: 1 }}>
                    {usedTruck ? `Truck: ${usedTruck}` : 'Dispatched'} {usedParty ? `· ${usedParty}` : ''}
                  </div>
                </div>
              </div>

              {linkedDispatch && onViewDispatch && (
                <button
                  type="button"
                  onClick={() => {
                    onClose();
                    onViewDispatch(linkedDispatch);
                  }}
                  style={{
                    background: 'var(--ios-purple, #af52de)',
                    color: '#ffffff',
                    border: 'none',
                    borderRadius: 8,
                    padding: '6px 10px',
                    fontSize: 12,
                    fontWeight: 600,
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 4,
                    flexShrink: 0,
                  }}
                >
                  <Truck size={13} />
                  <span>View</span>
                  <ExternalLink size={12} />
                </button>
              )}
            </div>
          ) : (
            <div
              style={{
                marginBottom: 16,
                padding: '10px 14px',
                borderRadius: 14,
                background: 'rgba(52, 199, 89, 0.1)',
                border: '0.5px solid rgba(52, 199, 89, 0.25)',
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                fontSize: 12,
                fontWeight: 600,
                color: 'var(--ios-green)',
              }}
            >
              <CheckCircle2 size={16} />
              <span>In Yard Stock · Available for Coal Blending</span>
            </div>
          )}

          {/* Hero Total Value Card */}
          <div
            style={{
              background: 'var(--fill-quaternary, rgba(120,120,128,0.08))',
              borderRadius: 18,
              padding: '18px 16px',
              textAlign: 'center',
              border: '0.5px solid var(--separator)',
              marginBottom: 18,
            }}
          >
            <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--label-secondary)', textTransform: 'uppercase', letterSpacing: 0.5 }}>
              Total Value (Coal + Loading + Fare)
            </div>
            <div
              style={{
                fontSize: 34,
                fontWeight: 800,
                color: 'var(--label-primary)',
                marginTop: 4,
                lineHeight: 1.1,
              }}
              className="tabular-nums"
            >
              {curSym} {formatAmountNumber(totalCost, settings)}
            </div>
            <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--ios-blue)', marginTop: 6 }} className="tabular-nums">
              Effective Landed Rate: {curSym} {formatAmountNumber(landedRate, settings)} / ton
            </div>
          </div>

          {/* Detailed Specifications Inset Table */}
          <div className="ios-card-grouped" style={{ overflow: 'hidden' }}>
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                padding: '12px 16px',
                borderBottom: '0.5px solid var(--separator)',
              }}
            >
              <span style={{ fontSize: 14, color: 'var(--label-secondary)' }}>Bought From</span>
              <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--label-primary)' }}>
                {lot.boughtFrom || lot.supplier || 'N/A'}
              </span>
            </div>

            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                padding: '12px 16px',
                borderBottom: '0.5px solid var(--separator)',
              }}
            >
              <span style={{ fontSize: 14, color: 'var(--label-secondary)', display: 'flex', alignItems: 'center', gap: 5 }}>
                <Calendar size={14} /> Entry Date
              </span>
              <span style={{ fontSize: 14, fontWeight: 600, color: 'var(--label-primary)' }}>
                {formatDisplayDate(lot.date)}
              </span>
            </div>

            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                padding: '12px 16px',
                borderBottom: '0.5px solid var(--separator)',
              }}
            >
              <span style={{ fontSize: 14, color: 'var(--label-secondary)', display: 'flex', alignItems: 'center', gap: 5 }}>
                <MapPin size={14} /> Stored At
              </span>
              <span style={{ fontSize: 14, fontWeight: 600, color: 'var(--label-primary)' }}>
                {lot.storedAt || mine?.location || 'Mine Yard'}
              </span>
            </div>

            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                padding: '12px 16px',
                borderBottom: '0.5px solid var(--separator)',
              }}
            >
              <span style={{ fontSize: 14, color: 'var(--label-secondary)' }}>Loaded / Billed Weight</span>
              <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--label-primary)' }} className="tabular-nums">
                {billedWeight.toFixed(2)} tons
              </span>
            </div>

            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                padding: '12px 16px',
                borderBottom: '0.5px solid var(--separator)',
              }}
            >
              <span style={{ fontSize: 14, color: 'var(--label-secondary)' }}>Received Weight</span>
              <div style={{ textAlign: 'right' }}>
                <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--label-primary)' }} className="tabular-nums">
                  {receivedWeight.toFixed(2)} tons
                </span>
                {Math.abs(weightDiff) > 0.01 && (
                  <div
                    style={{
                      fontSize: 11,
                      fontWeight: 600,
                      color: weightDiff > 0 ? 'var(--ios-green)' : 'var(--ios-red)',
                    }}
                  >
                    {weightDiff > 0 ? `+${weightDiff.toFixed(2)}t excess` : `${weightDiff.toFixed(2)}t shortage`}
                  </div>
                )}
              </div>
            </div>

            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                padding: '12px 16px',
                borderBottom: '0.5px solid var(--separator)',
              }}
            >
              <span style={{ fontSize: 14, color: 'var(--label-secondary)' }}>Base Rate per Ton</span>
              <span style={{ fontSize: 14, fontWeight: 600, color: 'var(--label-primary)' }} className="tabular-nums">
                {curSym} {formatAmountNumber(baseRate, settings)} / ton
              </span>
            </div>

            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                padding: '12px 16px',
                borderBottom: '0.5px solid var(--separator)',
              }}
            >
              <span style={{ fontSize: 14, color: 'var(--label-secondary)' }}>Base Coal Cost</span>
              <span style={{ fontSize: 14, fontWeight: 600, color: 'var(--label-primary)' }} className="tabular-nums">
                {curSym} {formatAmountNumber(baseCoalCost, settings)}
              </span>
            </div>

            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                padding: '12px 16px',
                borderBottom: '0.5px solid var(--separator)',
              }}
            >
              <span style={{ fontSize: 14, color: 'var(--label-secondary)' }}>Loading Amount</span>
              <span style={{ fontSize: 14, fontWeight: 600, color: 'var(--label-primary)' }} className="tabular-nums">
                {curSym} {formatAmountNumber(loading, settings)}
              </span>
            </div>

            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                padding: '12px 16px',
              }}
            >
              <span style={{ fontSize: 14, color: 'var(--label-secondary)' }}>Fare / Freight</span>
              <span style={{ fontSize: 14, fontWeight: 600, color: 'var(--label-primary)' }} className="tabular-nums">
                {curSym} {formatAmountNumber(fare, settings)}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* ── iOS-Styled Linked Stock Entry Deletion Alert ── */}
      <IOSConfirmModal
        isOpen={showUsedAlert}
        title="Cannot Delete Stock Entry"
        message={`Cannot delete this stock entry because it is actively used in Dispatch #${usedTruck || ''}. Remove or reassign it from the dispatch first.`}
        confirmText="OK"
        singleButton
        destructive={false}
        countdownSeconds={0}
        icon="warning"
        onConfirm={() => setShowUsedAlert(false)}
        onCancel={() => setShowUsedAlert(false)}
      />
    </div>
  );
}
